import { businessCategories, categoryTags, overpassSelectors, businessIndustry } from "@/lib/business-categories";
import { env } from "@/lib/server-env";
import { NextResponse } from "next/server";
import { fetchProviderJSON, firstProviderJSON, DiscoveryProviderError } from "@/lib/discovery-http";
import { getChatGPTUser } from "../../chatgpt-auth";
const config=()=>env as unknown as {GOOGLE_PLACES_API_KEY?:string;NOMINATIM_URL?:string;OVERPASS_URL?:string};
export async function GET(){return NextResponse.json({placesConnected:Boolean(config().GOOGLE_PLACES_API_KEY),publicDirectory:true});}
export async function POST(request:Request){if(!await getChatGPTUser())return NextResponse.json({error:"Sign in to search."},{status:401});try{const b=await request.json() as {category?:string;location?:string;radius?:number;limit?:number;provider?:string};const category=b.category||"all",location=String(b.location||"").trim(),radius=Number(b.radius||10),limit=Number(b.limit||25),provider=b.provider||"public";if(!categoryTags(category)||location.length<3||location.length>150||![5,10,15,25,50].includes(radius)||![10,25,50].includes(limit)||!["public","google"].includes(provider))return NextResponse.json({error:"Choose a business category, location, radius and result limit."},{status:400});
if(provider==="google"){const key=config().GOOGLE_PLACES_API_KEY;if(!key)return NextResponse.json({error:"Google Places is not connected. Choose Public directory to search now."},{status:503});const data=await fetchProviderJSON("https://places.googleapis.com/v1/places:searchText",{method:"POST",headers:{"Content-Type":"application/json","X-Goog-Api-Key":key,"X-Goog-FieldMask":"places.id,places.displayName,places.formattedAddress,places.nationalPhoneNumber,places.websiteUri,places.location,places.googleMapsUri"},body:JSON.stringify({textQuery:`${category==="all"?"local businesses companies shops and professional services":businessCategories.find(c=>c.id===category)!.label} in ${location}`,pageSize:Math.min(limit,20)})}) as {places?:Array<{id:string;displayName?:{text?:string};formattedAddress?:string;nationalPhoneNumber?:string;websiteUri?:string;location?:{latitude:number;longitude:number};googleMapsUri?:string}>};return NextResponse.json({provider:"Google Places",storageAllowed:false,location,results:(data.places||[]).map(p=>({id:p.id,company:p.displayName?.text||"Business",address:p.formattedAddress||"",phone:p.nationalPhoneNumber||"",website:p.websiteUri||"",email:"",latitude:String(p.location?.latitude??""),longitude:String(p.location?.longitude??""),sourceUrl:p.googleMapsUri||"",industry:category==="all"?"Business · qualification pending":businessCategories.find(c=>c.id===category)!.label}))});}
const resultKey=`results:v2:${category}:${location.toLowerCase()}:${radius}:${limit}`;
const prior=await env.DB!.prepare("SELECT payload FROM discovery_cache WHERE cache_key=? AND expires_at>?").bind(resultKey,Date.now()).first<{payload:string}>();
if(prior){try{return NextResponse.json({...JSON.parse(prior.payload),cached:true});}catch{}}
const gate=await env.DB!.prepare("INSERT OR IGNORE INTO discovery_cache (cache_key,payload,expires_at) VALUES (?, '', ?)").bind(`rate:${Math.floor(Date.now()/1000)}`,Date.now()+60000).run();if(!gate.meta.changes)return NextResponse.json({error:"Another search just started. Wait a few seconds and try again."},{status:429});
const cacheKey=`geocode:${location.toLowerCase()}`;const cached=await env.DB!.prepare("SELECT payload FROM discovery_cache WHERE cache_key=? AND expires_at>?").bind(cacheKey,Date.now()).first<{payload:string}>();let geo:{lat:string;lon:string;display_name:string}[];if(cached)geo=JSON.parse(cached.payload);else{
 const photon=new URL("https://photon.komoot.io/api/");photon.searchParams.set("q",location);photon.searchParams.set("limit","1");
 try{const data=await fetchProviderJSON(photon.toString(),undefined,10000) as {features?:Array<{geometry?:{coordinates?:number[]};properties?:Record<string,string>}>};
 if(!Array.isArray(data.features))throw new DiscoveryProviderError("Location search is temporarily unavailable.");
 geo=data.features.filter(f=>f.geometry?.coordinates?.length===2).map(f=>({lat:String(f.geometry!.coordinates![1]),lon:String(f.geometry!.coordinates![0]),display_name:[f.properties?.name,f.properties?.city,f.properties?.state,f.properties?.country].filter(Boolean).join(", ")}));
 }catch{const u=new URL(config().NOMINATIM_URL||"https://nominatim.openstreetmap.org/search");u.searchParams.set("q",location);u.searchParams.set("format","jsonv2");u.searchParams.set("limit","1");geo=await fetchProviderJSON(u.toString(),{headers:{"User-Agent":"SUHLeadFlow/1.0 (https://suh-leadflow.lifemantra-04.chatgpt.site)"}},10000) as typeof geo;if(!Array.isArray(geo))throw new DiscoveryProviderError("Location search is temporarily unavailable.");}
 if(geo.length)await env.DB!.prepare("INSERT OR REPLACE INTO discovery_cache(cache_key,payload,expires_at) VALUES(?,?,?)").bind(cacheKey,JSON.stringify(geo),Date.now()+86400000).run();
}
if(!geo.length)return NextResponse.json({error:"Location not found. Include city, state and country."},{status:404});const lat=Number(geo[0].lat),lon=Number(geo[0].lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))throw new DiscoveryProviderError("Could not resolve this location. Include city, state and country.");let data:{elements?:Array<{type:string;id:number;lat?:number;lon?:number;center?:{lat:number;lon:number};tags?:Record<string,string>}>;remark?:string};
let basicListings=false;
try{
 const u=new URL("https://photon.komoot.io/reverse");u.searchParams.set("lat",String(lat));u.searchParams.set("lon",String(lon));u.searchParams.set("radius",String(radius));u.searchParams.set("limit",String(limit));for(const tag of categoryTags(category)!)u.searchParams.append("osm_tag",tag);
 const d=await fetchProviderJSON(u.toString(),undefined,12000) as {features?:Array<{geometry?:{coordinates?:number[]};properties?:{name?:string;osm_key?:string;osm_value?:string;osm_type?:string;osm_id?:number;housenumber?:string;street?:string;district?:string;city?:string;state?:string;country?:string;postcode?:string;extra?:Record<string,string>}}>};
 if(!Array.isArray(d.features))throw new DiscoveryProviderError("Directory returned an unexpected response.");
 const elements=d.features.filter(f=>f.properties?.name&&f.properties.osm_id&&["N","W","R"].includes(f.properties.osm_type||"")&&f.geometry?.coordinates?.length===2).map(f=>{const p=f.properties!;return {type:({N:"node",W:"way",R:"relation"} as Record<string,string>)[p.osm_type!],id:p.osm_id!,lat:f.geometry!.coordinates![1],lon:f.geometry!.coordinates![0],tags:{...p.extra,...(p.osm_key?{[p.osm_key]:p.osm_value||""}:{}),name:p.name!,"addr:housenumber":p.housenumber||"","addr:street":p.street||"","addr:suburb":p.district||"","addr:city":p.city||"","addr:state":p.state||"","addr:country":p.country||"","addr:postcode":p.postcode||""}};});
 data={elements};basicListings=true;
}catch{
 const query=`[out:json][timeout:15];(${overpassSelectors(category).map(tag=>`nwr${tag}["name"](around:${radius*1000},${lat},${lon});`).join("")});out center ${limit};`;data=await firstProviderJSON([config().OVERPASS_URL||"https://overpass.private.coffee/api/interpreter","https://maps.mail.ru/osm/tools/overpass/api/interpreter"],{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded","User-Agent":"SUHLeadFlow/1.0 (https://suh-leadflow.lifemantra-04.chatgpt.site)"},body:new URLSearchParams({data:query}).toString()},18000,value=>Boolean(value&&typeof value==="object"&&Array.isArray((value as {elements?:unknown}).elements))) as {elements?:Array<{type:string;id:number;lat?:number;lon?:number;center?:{lat:number;lon:number};tags?:Record<string,string>}>;remark?:string};
}
if(data.remark&&!data.elements?.length)throw new DiscoveryProviderError("The directory timed out. Try a smaller radius.");const inRadius=(p:{lat?:number;lon?:number;center?:{lat:number;lon:number}})=>{const a=p.lat??p.center?.lat,b=p.lon??p.center?.lon;if(a===undefined||b===undefined)return false;const r=Math.PI/180,h=Math.sin((a-lat)*r/2)**2+Math.cos(lat*r)*Math.cos(a*r)*Math.sin((b-lon)*r/2)**2;return 12742*Math.asin(Math.min(1,Math.sqrt(h)))<=radius;};const results=(data.elements||[]).filter(inRadius).slice(0,limit).map(p=>{const t=p.tags||{};return {id:`${p.type}/${p.id}`,company:t.name||"Business",address:[t["addr:housenumber"],t["addr:street"],t["addr:suburb"],t["addr:city"],t["addr:state"],t["addr:postcode"]].filter(Boolean).join(", "),city:t["addr:city"]||"",state:t["addr:state"]||"",country:t["addr:country"]||"",phone:t["contact:phone"]||t.phone||"",website:t["contact:website"]||t.website||"",email:t["contact:email"]||t.email||"",latitude:String(p.lat??p.center?.lat??""),longitude:String(p.lon??p.center?.lon??""),sourceUrl:`https://www.openstreetmap.org/${p.type}/${p.id}`,industry:businessIndustry(t,category)};});await env.DB!.prepare("DELETE FROM discovery_cache WHERE expires_at<?").bind(Date.now()).run();const payload={provider:"OpenStreetMap",storageAllowed:true,location:geo[0].display_name,results,basicListings,partial:Boolean(data.remark)};
if(!data.remark)await env.DB!.prepare("INSERT OR REPLACE INTO discovery_cache(cache_key,payload,expires_at) VALUES(?,?,?)").bind(resultKey,JSON.stringify(payload),Date.now()+900000).run();
return NextResponse.json(payload);
}catch(e){return NextResponse.json({error:e instanceof DiscoveryProviderError?e.message:"Business search could not complete. Please try again. If this persists, connect Google Places."},{status:502});}}
